"""Build the static venture atlas from the public, curated data file (Python 3.9+)."""
from pathlib import Path
import html,json,re,math,hashlib
ROOT=Path(__file__).resolve().parents[1]
SHEET='https://docs.google.com/spreadsheets/d/1Gg83iAAs0g5xVeNzanD90TTprQ0l70u-OZmDJbaJ2nc/edit?usp=drivesdk'
def e(s):return html.escape(str(s),quote=True)
def usd(n):return f'{n:,.0f}'.replace(',','.')+' USD'
def dl(label,value,cls=''):return '<dl'+(' class="'+e(cls)+'"' if cls else '')+'><dt>'+e(label)+'</dt><dd>'+e(value)+'</dd></dl>'
def asset(name):
 return 'assets/'+name+'?v='+hashlib.sha256((ROOT/'assets'/name).read_bytes()).hexdigest()[:10]
def page_head(title,css='style.css',interactive=True):
 return '<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Girişimlerini yeniden keşfet: yazılım türü, amacı, somut kullanım örneği ve gelir stratejisi."><meta name="color-scheme" content="light"><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><title>'+e(title)+' · BPGPT</title><link rel="stylesheet" href="'+asset(css)+'">'+('<script src="'+asset('app.js')+'" defer></script>' if css=='style.css' and interactive else ('<link rel="stylesheet" href="'+asset('tokens.css')+'">' if css!='style.css' else ''))+'</head>'
def main():
 data=json.loads((ROOT/'data/girisimler.json').read_text());ps=data['projects'];criteria=data['criteria'];settings=data['settings'];groups=data['groups']
 assert len(ps)==46 and len({p['id'] for p in ps})==46
 tokens=(ROOT/'assets/tokens.css').read_text()
 style=ROOT/'assets/style.css';style.write_text(re.sub(r'@import url\("tokens.css[^"]*"\);','@import url("tokens.css?v='+hashlib.sha256(tokens.encode()).hexdigest()[:10]+'");',style.read_text()))
 teal=re.search(r'--teal:([^;]+)',tokens)[1];white=re.search(r'--white:([^;]+)',tokens)[1]
 (ROOT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="'+teal+'"/><path d="M9 7h7c5 0 8 5 4 9 5 4 2 9-4 9H9zm5 4v4h2c3 0 3-4 0-4zm0 8v3h3c3 0 3-3 0-3z" fill="'+white+'"/></svg>')
 for p in ps:
  assert len(p['workflow'])==3 and len(p['scoreReasons'])==16 and len(p['scores'])==16
  assert p['group'] in dict(groups)
  assert all(isinstance(v,(int,float)) and not isinstance(v,bool) and math.isfinite(v) for v in [p['cashScore'],p['selfScore'],*p['scores']])
  assert all(0<=v<=5 for v in p['scores']) and 0<=p['cashScore']<=100 and 0<=p['selfScore']<=100
  assert all(r['criterion']==c[0] and r['score']==v for r,c,v in zip(p['scoreReasons'],criteria,p['scores']))
  assert all(p[k].strip() for k in ['softwareType','plainDefinition','purpose','audience','concreteExample','currentState','proposedFirstOffer'])
 nav='<a class="skip" href="#icerik">İçeriğe geç</a><header class="masthead wrap"><a class="wordmark" href="index.html" aria-label="BPGPT ana sayfa">BPGPT</a><nav aria-label="Ana menü"><a href="#projeler">Girişimler</a><a href="strateji.html">Strateji</a><a href="'+SHEET+'">Google Sheets’te aç</a></nav></header>'
 preview=[]
 for name in ['QRAL']:
  p=next(p for p in ps if name.lower() in p['title'].lower())
  preview.append('<div class="preview-entry"><span class="preview-number">34 / 46</span><strong>'+e(name)+'</strong><span>'+e(p['softwareType'])+'</span><p>'+e(p['plainDefinition'].split('. ')[0].rstrip('.')+'.')+'</p><a href="projeler/'+p['id']+'.html">Bu girişimi tanı</a></div>')
 metrics='<dl class="hero-metrics" aria-label="Portföy özeti"><div><dt>'+str(len(ps))+'</dt><dd>girişim ailesi</dd></div><div><dt>'+str(len(groups))+'</dt><dd>ürün alanı</dd></div><div><dt>'+str(len(criteria))+'</dt><dd>değerlendirme kriteri</dd></div></dl>'
 hero='<section class="hero wrap" aria-labelledby="baslik"><div class="hero-copy"><p class="eyebrow">GİRİŞİM ATLASI / 01 EKİM 2026</p><h1 id="baslik">Bu projeler ne işe yarıyor?</h1><p class="intro">Her girişimin ne yazılımı olduğunu, kimin hangi işini çözdüğünü ve bugün ne durumda bulunduğunu öğren.</p><div class="actions"><a class="button" href="#projeler">Girişimleri tanı</a><a class="button secondary" href="'+SHEET+'">Google Sheets’te aç</a></div>'+metrics+'</div><figure class="atlas-preview"><figcaption>BİR ÖRNEKLE BAŞLA / QRAL</figcaption>'+''.join(preview)+'</figure></section>'
 guide='<section class="quick-guide wrap" aria-label="Okuma rehberi"><div><span class="guide-index" aria-hidden="true">01</span><strong>Bu nedir?</strong><p>Bir tarayıcı uzantısı mı, işletme uygulaması mı, yoksa henüz bir fikir mi?</p></div><div><span class="guide-index" aria-hidden="true">02</span><strong>Neden var?</strong><p>Kimin hangi işini kolaylaştırır? Somut bir kullanım örneğiyle hatırla.</p></div><div><span class="guide-index" aria-hidden="true">03</span><strong>Nasıl gelir üretir?</strong><p>Mevcut yazılımdan önerilen ücretli işe geçişi ve değerlendirmeyi ayrı incele.</p></div></section>'
 controls='<div class="toolbar" hidden><div class="views" role="group" aria-label="Okuma görünümü"><button id="view-discover" type="button" aria-pressed="true">Projeleri tanı</button><button id="view-decide" type="button" aria-pressed="false">Gelir açısından karşılaştır</button></div><div><label for="project-search">İsim, yazılım türü veya çözdüğü iş</label><input id="project-search" type="search" placeholder="Örneğin: QRAL, tarayıcı, restoran" autocomplete="off"></div><div class="sorts decision-only" role="group" aria-label="Proje sıralaması"><button id="sort-cash" type="button" aria-pressed="true">Satış uyumu</button><button id="sort-self" type="button" aria-pressed="false">Düşük satış emeği</button></div></div><div class="filters" role="group" aria-label="Girişim alanı" hidden>'+''.join('<button type="button" data-filter="'+e(key)+'" aria-pressed="'+('true' if key=='all' else 'false')+'">'+e(label)+'</button>' for key,label in [('all','Tümü')]+groups)+'</div><div class="result-line"><p id="result-count" class="result-count" role="status" aria-live="polite">46 girişim gösteriliyor</p><button id="reset-filters" class="text-button" type="button" hidden>Filtreleri temizle</button></div><noscript><p class="noscript-note">Arama ve görünüm değiştirme için JavaScript gerekir. Tüm girişimler ve ayrıntıları aşağıda okunabilir.</p></noscript><p id="no-results" class="empty" hidden>Bu aramayla eşleşen girişim yok. Filtreleri temizleyebilir veya başka bir iş tanımı arayabilirsiniz.</p>'
 reached=sum(p['finance']['netCashUSD']>=settings['targetNetCash'] for p in ps)
 banner='<aside class="decision-banner decision-only"><strong>Nitel uygunluk, gelir gerçekleşme oranı değildir.</strong><p>Örnek hedef: '+usd(settings['targetNetCash'])+' / '+str(settings['horizonMonths'])+' ay; haftada '+str(settings['weeklyHours'])+' saat. Varsayılan senaryoda hedefe ulaşan aile: '+str(reached)+'. Gerçek talep ve tahsilat doğrulanmadı. Kapılar geçilmeden yatırım sırası oluşmaz.</p><a href="yontem.html">Puan ile nakit hesabının farkını oku</a></aside>'
 rows=[];score_sections=[]
 for index,p in enumerate(ps,1):
  f=p['finance'];required=f['requiredSales'];capacity=f['capacitySales'];gap=max(0,settings['targetNetCash']-f['netCashUSD']);fit='Ticari kapsam dışında' if p['gate']=='Kapsam kaydı' else ('Saat kapasitesi yetersiz' if required is None or required>capacity else 'Saat kapasitesine sığıyor; talep doğrulanmadı')
  finance_text='Örnek '+str(f['scenarioSales'])+' alıcı · Net nakit '+usd(f['netCashUSD'])+' · Hedef açığı '+usd(gap)
  capacity_text='Hedef için gereken satış: '+str(required if required is not None else 'hesaplanamıyor')+' / saat kapasitesi: '+str(capacity)+'. '+fit+'.'
  scores='<span class="decision-summary"><span class="score-line"><span>Satış uyumu <strong>'+f"{p['cashScore']:.1f}"+'</strong>/100</span><span>Düşük satış emeği <strong>'+f"{p['selfScore']:.1f}"+'</strong>/100</span></span><span class="cash-summary">'+e(finance_text)+'</span><span class="cash-summary">'+e(capacity_text)+'</span></span>'
  fields=[('Ekonomik alıcı ve satın alma tetikleyicisi',p['buyer']+' · '+p['trigger']),('İlk ücretli teklif',p['primaryOffer']),('Düşük maliyetli erişim kanalı',p['channel']),('Doğrulama kapısı',p['gateReason']),('İlk deney',p['nextTest']),('Sonraki ürünleşme aşaması',p['reason'])]
  commercial='<details class="commercial-details"><summary>Gelir stratejisi ve değerlendirme</summary><div class="commercial-body"><p class="method-note">'+e(p['gate'])+' · Puanlar uzman hipotezi; finans örnek varsayım hesabıdır.</p><div class="detail-grid">'+''.join(dl(k,v) for k,v in fields)+'</div><p class="cash-summary">'+e(finance_text+' · '+capacity_text)+'</p><p class="detail-footer">'+e(p['evidence'])+'</p><a href="puanlar.html#puan-'+p['id']+'">16 kriterin puanını ve gerekçesini incele</a></div></details>'
  identity='<div class="identity-grid">'+dl('Varlık nedeni · hangi iş için?',p['purpose'],'project-purpose')+dl('Kim kullanır?',p['audience'])+'<div><p class="detail-label">Kullanım akışı</p><ol class="workflow">'+''.join('<li>'+e(s)+'</li>' for s in p['workflow'])+'</ol></div>'+dl('Önerilen ilk ücretli iş',p['proposedFirstOffer'])+'</div><aside class="project-example"><strong>Somut kullanım örneği</strong><p>'+e(p['concreteExample'])+'</p></aside><p class="current-state"><strong>Bugünkü durum:</strong> '+e(p['currentState'])+'</p>'
  search=' '.join(p[k] for k in ['title','softwareType','plainDefinition','purpose','audience','primaryOffer','buyer','channel'])
  rows.append('<details class="project-row" id="proje-'+p['id']+'" data-group="'+e(p['group'])+'" data-name="'+e(p['title'])+'" data-order="'+str(index)+'" data-cash="'+str(p['cashScore'])+'" data-self="'+str(p['selfScore'])+'"><summary><span class="project-heading"><span class="project-number">'+f'{index:02d}'+'</span><span class="project-copy"><span class="project-meta"><span class="project-type">'+e(p['softwareType'])+'</span></span><span class="project-name">'+e(p['title'])+'</span><span class="plain-definition">'+e(p['plainDefinition'])+'</span>'+scores+'</span><span class="expand" aria-hidden="true"></span></span></summary><div class="project-detail"><p><a class="project-guide-link" href="projeler/'+p['id']+'.html">Bu proje nedir? Ayrıntılı açıklamayı aç</a></p>'+identity+commercial+'</div></details>')
  table='<div class="table-wrap" tabindex="0" role="region" aria-label="'+e(p['title']+' kriter gerekçeleri')+'"><table><thead><tr><th scope="col">Kriter</th><th scope="col">0–5 puan</th><th scope="col">Gerekçe · uzman hipotezi</th></tr></thead><tbody>'
  for c,s,r in zip(criteria,p['scores'],p['scoreReasons']):table+='<tr><th scope="row">'+e(c[0]+' · '+c[2])+'</th><td>'+str(s)+'</td><td>'+e(r['reason'])+'</td></tr>'
  table+='</tbody></table></div>'
  score_sections.append('<section><h2 id="puan-'+p['id']+'">'+e(p['title'])+'</h2><p>'+e(p['plainDefinition'])+'</p><p>Satış uyumu '+f"{p['cashScore']:.1f}"+'/100 · Düşük satış emeği '+f"{p['selfScore']:.1f}"+'/100. Bunlar gelir ihtimali veya finansal hedef gerçekleşme yüzdesi değildir.</p>'+table+'<p><a href="index.html#proje-'+p['id']+'">Girişim açıklamasına dön</a></p></section>')
 resources='<div class="resources"><a href="strateji.html">Birleşik strateji</a><a href="kriterler.html">16 kriter ve 100 soru</a><a href="puanlar.html">Tüm puan gerekçeleri</a><a href="kapsam.html">Kaynak kapsamı</a><a href="'+SHEET+'">Google Sheets’te aç</a></div>'
 body=page_head('Girişim atlası')+'<body data-view="discover">'+nav+'<main id="icerik">'+hero+guide+'<section class="comparison wrap" id="projeler" aria-labelledby="project-title"><div class="section-head"><div><p class="section-kicker">PORTFÖY / 46 GİRİŞİM</p><h2 id="project-title">Girişimlerini tanı.</h2></div><p>Yazılım türü · amaç · somut örnek</p></div>'+controls+banner+'<div id="project-list">'+''.join(rows)+'</div>'+resources+'</section></main><footer><div class="wrap footer-layout"><div><a class="wordmark" href="index.html">BPGPT / GİRİŞİM ATLASI</a><p>46 ailede toplanan ürün, prototip, hizmet ve iç varlıklar. Aynı projenin sürümleri ayrı girişim gibi sayılmaz.</p></div><p>Tanımlar kaynak belgelerden derlenmiştir. Bugünkü varlık ile önerilen ürün ayrı gösterilir. Gerçek kullanıcı, tahsilat ve kurumsal olgunluk doğrulanmış sayılmaz. Özgün kaynak klasörler değiştirilmemiştir.</p></div></footer></body></html>'

 (ROOT/'projeler').mkdir(exist_ok=True)
 for p in ps:
  content=page_head(p['title'],interactive=False).replace('href="assets/','href="../assets/').replace('src="assets/','src="../assets/')
  content+='<body><a class="skip" href="#icerik">İçeriğe geç</a><header class="masthead wrap"><a class="wordmark" href="../index.html">BPGPT</a><nav aria-label="Ana menü"><a href="../index.html#proje-'+p['id']+'">Tüm girişimlere dön</a><a href="'+SHEET+'">Google Sheets’te aç</a></nav></header><main class="wrap venture-guide" id="icerik"><p class="eyebrow">GİRİŞİM REHBERİ / '+e(p['softwareType'])+'</p><h1>'+e(p['title'])+'</h1><p class="guide-definition">'+e(p['plainDefinition'])+'</p><section class="guide-section"><h2>Neden var?</h2><p>'+e(p['purpose'])+'</p></section><section class="guide-section"><h2>Kim kullanır?</h2><p>'+e(p['audience'])+'</p></section><section class="guide-section"><h2>Nasıl kullanılır?</h2><ol class="workflow">'+''.join('<li>'+e(step)+'</li>' for step in p['workflow'])+'</ol></section><section class="project-example"><h2>Bir kullanım örneği</h2><p>'+e(p['concreteExample'])+'</p></section><section class="guide-section"><h2>Bugün ne durumda?</h2><p>'+e(p['currentState'])+'</p></section><section class="guide-section"><h2>Nasıl bir işe dönüşebilir?</h2><p>'+e(p['proposedFirstOffer'])+'</p><p class="method-note">Bu bölüm önerilen ilk ücretli iştir; hazır ürün, gerçek talep veya gelir sonucu anlamına gelmez.</p><a class="project-guide-link" href="../index.html#proje-'+p['id']+'">Gelir stratejisi ve değerlendirmeye dön</a></section></main><footer><div class="wrap"><p>Mevcut varlık ile önerilen iş ayrı anlatılır. Bir plan veya prototip, tamamlanmış yazılım olarak sunulmaz.</p></div></footer></body></html>'
  (ROOT/'projeler'/(p['id']+'.html')).write_text(content)
 (ROOT/'index.html').write_text(body)
 scorepage=page_head('Proje puanları ve gerekçeleri','document.css')+'<body><a class="skip" href="#icerik">İçeriğe geç</a><header class="wrap"><p class="brand">BPGPT / DEĞERLENDİRME</p>'+resources+'</header><main class="wrap" id="icerik"><h1>Tercih puanlarının gerekçeleri.</h1><p>46 aile, 16 kriter. Puanlar geçici uzman yorumu; bütün ticari kapılar doğrulanmadan yalnız deney durumundadır. 4–5 puan dış kabul/ödeme kanıtı gerektirir; bu değerlendirmede kullanılmamıştır.</p><p><a href="kriterler.html">Kriterlerin 0–5 ölçütlerini incele</a></p>'+''.join(score_sections)+'</main></body></html>'
 (ROOT/'puanlar.html').write_text(scorepage)
 total=sum((ROOT/p).stat().st_size for p in ['index.html','assets/style.css','assets/tokens.css','assets/app.js','assets/favicon.svg'])
 assert total<200000,f'Initial route exceeds 200,000 raw bytes: {total}'
 print(json.dumps({'projects':len(ps),'definitions':len(ps),'initialRawBytes':total,'htmlBytes':len(body.encode()),'scorePageBytes':len(scorepage.encode())}))
if __name__=='__main__':main()
